[package]
name = "lnd_rust_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "lnd_rust_wrapper"
path = "src/lib.rs"

[[bin]]
name = "lnd_rust_wrapper"
path = "src/main.rs"

[build-dependencies]
bindgen = "0.60"

[dependencies]
lnd_grpc_rust = "2.7.0"
