[package]
name = "lnd_rust_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "lnd_rust_wrapper"
path = "src/lib.rs"

[[bin]]
name = "lnd_rust_wrapper"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
libc = "0.2"

[build-dependencies]
bindgen = "0.60"
